type_mapping = {
    'bigint': 'long',
    'binary': 'byte[]',
    'bit': 'bool',
    'char': 'string',
    'date': 'DateTime',
    'datetime': 'DateTime',
    'datetime2': 'DateTime',
    'decimal': 'decimal',
    'float': 'double',
    'image': 'byte[]',
    'int': 'int',
    'money': 'decimal',
    'nchar': 'string',
    'ntext': 'string',
    'numeric': 'decimal',
    'nvarchar': 'string',
    'real': 'float',
    'smalldatetime': 'DateTime',
    'smallint': 'short',
    'smallmoney': 'decimal',
    'text': 'string',
    'time': 'TimeSpan',
    'timestamp': 'byte[]',
    'tinyint': 'byte',
    'uniqueidentifier': 'Guid',
    'varbinary': 'byte[]',
    'varchar': 'string'
}

